apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-be-cm
  namespace: backend

data:
  mysqlHost: {{ .Values.config.mysqlHost | quote }}
  mysqlUsername: {{ .Values.config.mysqlUsername | quote }}
