apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-be-cm
  namespace: backend
data:
  mysqlHost: jdbc:mysql://<YOUR-RDS-ENDPOINT>:3306/studentdb?createDatabaseIfNotExist=true
  mysqlUname: admin